apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fleetman-staff-service  # "just" a name for this VirtualService
  namespace: default
spec:
  hosts:
    - fleetman-staff-service.default.svc.cluster.local # The Service DNS (ie the regular K8S Service) name that were applying
  http:
    - route:
        - destination:
            host: fleetman-staff-service.default.svc.cluster.local # The Target DNS name
            subset: all-staff-service-pods # The name defined in the DestionationRule
          # weight: 100 not needed if there's only one
---
kind: DestinationRule   # Defining which pods should be part of each subset
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-staff-service  # "just" a name for this DestinationRule
  namespace: default
spec:
  host: fleetman-staff-service  # Service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "x-myval"
  subsets:
    - labels:    # SELECTOR.
        app: staff-service  #  find pods with label "safe"
      name: all-staff-service-pods